### ISSUE TITLE
Labels are not included in OBJ file.

### ISSUE THREAD

**Issue by rdnelson** [hasithvm/lasm#10]
When assembling a file with labels, the label name is missing from field 4 of the Virgo OBJ file.

Input:

Message: .DB Hello World!$

Expected output:

```
^_0000^_^_13^_^_48656c6c6f20576f726c642124^_^_Message^_^_Hello World!$^_^_20^_
```

Actual Output:

```
^_0000^_^_13^_^_48656c6c6f20576f726c642124^_^_^_^_Hello World!$^_^_20^_
```

**Comment by hasithvm** [comment]
Fixed in f29593fd6087e3be97f6ca3b3a8b0be3197cb94d
