### ISSUE TITLE
Assembler stops assembling after a failure, but still outputs a file

### ISSUE THREAD

**Issue by DarrenStahl** [hasithvm/lasm#13]
The assembler continues to assemble after a failure, which can cause odd behaviors. Ex: "ERROR: Undefined label" on labels that are defined fine, but used before the definition, and the crash occurs between the two.

Repro:

```
JMP testLabel
ADD AX, 0xFAILURE
testLabel:
NOP
```

Result:

```
ERROR: lasm-parser (2) syntax error, unexpected TEXT, expecting DIRECTIVE
ERROR: Undefined label testLabel
```

Unexpected: error about undefined label.

The assembler still spits out an OBJ file which is incorrect, but can still be loaded and run, but is missing the instructions that caused the failure. When the assembler fails, there should be no output.

**Comment by hasithvm** [comment]
Fixed in commit 5b91bf7bff45008cd073ef757d595defd41c9ddd
