### ISSUE TITLE
0xB8+ encoding encodes immediate values with incorrect endianness.

### ISSUE THREAD

**Issue by rdnelson** [hasithvm/lasm#22]
Steps to reproduce:

Assemble:

```
mov ax, 0x4e9
```

Expected encoding:

```
0xB8 E9 04
```

Actual encoding:

```
0xB8 04 E9
```

**Comment by hasithvm** [comment]
Tracking this bug now. This seems to be symptomatic of larger issues with the opcode generation mechanisms.

**Comment by hasithvm** [comment]
Fixed in ad0a983342573ec43c470c5e8e5cd8de2b613e9f
