### ISSUE TITLE
Can you permit old in/out syntax as well?

### ISSUE THREAD

**Issue by jrgreen7** [hasithvm/lasm#4]
I assume you've changed the in/out instruction syntax. Would it be possible to also accept the syntax used in the course? Not a big issue, but may avoid a headache if I forget to update a slide or lab...

thanks

**Comment by hasithvm** [comment]
After talking with @rdnelson  and @DarrenStahl, we've come to the following conclusion about OUT and IN.
1. The currently implemented syntax (OUT DX,AL)  and (IN AL, DX) correspond to the 8086 encoding of instructions; it's an implicit operand instruction, and the encoding reflects that. The argument for leaving it as per the 8086 specification is that the actual instruction microcode takes care of the addressing, and the input for the microcode is in DX and AL. .
2. Switching to the [DX] style syntax is potentially confusing for students. As an example, consider

``` asm
out [DX], AL
```

Based on the square brackets, the initial understanding is that this instruction is saving AL at the address in DX, whereas, out performs an I/O operation.  Leaving it as the original 8086 encoding reduces confusion if it's actually writing to memory or is performing an I/O operation.

**Comment by hasithvm** [comment]
Closed, marked as a design issue. Will not change
